name: labhouse_combinable_reorderable_scroll
description: Provides a ReorderableCombinableGrid  and a ReorderableCombinableList along with the Sliver versions. They work as the ReorderableList from flutter works but with the ability to combine two items too, not only reorder them.
homepage: https://github.com/LabhouseMobile/labhouse-combinable-reorderable-scroll.git
repository: https://github.com/LabhouseMobile/labhouse-combinable-reorderable-scroll.git
version: 1.0.6

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
